### ISSUE TITLE
URL of tutorial is broken

### ISSUE THREAD

**Issue by imranakram** [chrisjmccormick/LSA_Classification#2]
Hi,

The URL in the description is not correct. http://mccormickml.com/tutorials/2016/03/26/lsa-for-text-classification-tutorial/

Br,
Imran

**Comment by chrisjmccormick** [comment]
Thanks for pointing that out, I've updated the link.

**Comment by imranakram** [comment]
It's still not updated. Could you please check that again?

**Comment by chrisjmccormick** [comment]
You're referring to the URL in the README.md file, right? I've updated that one.

The correct URL is: http://mccormickml.com/2016/03/25/lsa-for-text-classification-tutorial/

**Comment by imranakram** [comment]
Ahan no I was pointing to the description of the repository :)
